### ISSUE TITLE
Cutadapt module for processing "traditional" illumina librairies?

### ISSUE THREAD

**Issue by mimouschka** [yoann-dufresne/amplicon_pipeline#23]
Hi Yoann (and Tristan),
Thanks for your great work :) would it be possible to add cutadapt as a module to be able to process non-tagged and directional librairies as well (the ones produced through 2 PCR steps, using 5' overhangs) ?

**Comment by yoann-dufresne** [comment]
Hi @mimouschka ,
Thanks for the kind words for this work.

Unfortunately, this work has been stopped a few years ago. Tristan and I were postdoc at the time and both of us moved to other labs to do other things. At the same time, our former lab has been closed and we don't have any founding to hire people on this topic.
So, I am trying to fix bugs when they raise from the code but no new development is planned for now. (Except if anybody with money wants to hire bioinformatics engineers to do the job (and maybe more !)).

The code is still open so, if you know anybody that have to time to modify it, I would be happy to help.

Yoann
