### ISSUE TITLE
Help with Mail Set-Up

### ISSUE THREAD

**Issue by cement-head** [yoann-dufresne/amplicon_pipeline#24]
I do not understand what you mean by the following:

Before deploying SLIM, you need to configure the mailing account that will be used for mailing service. We advise to use gmail, as it is already set in the 'server/config.js' file. This file need to be updated with your 'user' and 'pass' credentials on the server:

exports.mailer = {
	host: 'smtp.gmail.com',
    port: 465,
    secure: true, // true for 465, false for other ports
    auth: {
        user: 'username',
        pass: 'password'
    }
}

Can you explain this?  What do mean by "credentials on the server:"?  Do you mean my specific credentials of my eMAIL account on the GMAIL server?

**Comment by yoann-dufresne** [comment]
The server is sending emails when computations are over.
So you need to setup an email address for the server (not your own !).
I recommend to create a specific email address for your slim server.
